# Generated by Django 5.1.6 on 2025-02-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Дата и время действия')),
                ('status', models.CharField(choices=[('created', 'Создана(получена от локального сервера)')], max_length=35, verbose_name='Статус')),
                ('change', models.JSONField()),
            ],
        ),
    ]
