# Generated by Django 5.1.6 on 2025-02-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='author',
            field=models.CharField(default='local', max_length=20, verbose_name='Источник изменения'),
            preserve_default=False,
        ),
    ]
